### ISSUE TITLE
Поправить ошибки в analysis_tools/Readme

### ISSUE THREAD

**Issue by zandreika** [Oskal174/staticProgramAnalysis#2]
Нашел две ошибки в описании анализатора Joern: пропущена запятая в выражении "граф вызовов граф структуры каталога исходного кода", а также грамматическая ошибка в выражении "реализацией этого функционала в виде база(базы) данных, удобной для анализа и пост-обработки."

**Comment by Oskal174** [comment]
Поправил, спасибо
